### PR TITLE
[MRG] Add Colab and Github link to the tutorial notebooks

### LINKED ISSUE #14: Colaboratory Notebooks for the tutorials
I noticed that for the [Jupyter Notebook tutorials](https://github.com/tensorflow/adanet/tree/master/adanet/examples/tutorials), there wasn't any corresponding Colaboratory notebook. It would be nice to have them for quickly getting started and for beginners, since setting up the notebooks locally require a lot of steps (install cuda, update protoc, update protobuf, etc.)

Would it be reasonable to add them? If so, I'd be happy to start a PR, if it's logistically possible.

Thank you!

### PR DESCRIPTION
**Pull request by xhluca**
## Description

There is currently no link to the Github repo, and to the colab link. This PR adds a link to both similar to [how Tensorflow does it](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/contrib/eager/python/examples/notebooks/custom_layers.ipynb).

Please view the change not through the file changed diff, but directly on [the branch](https://github.com/xhlulu/adanet/tree/update-tutorials/adanet/examples/tutorials).

## Notes

This also fixes #13 , so if this is merged before then #13 can be closed.

Closes #14 

## Screenshots

Here are screenshots of the changes:

capture
capture2

### CODE REVIEW

**Comment by cweill** [comment]
Thanks for this pull request. It might be a few days until I can merge this, since our PR workflow is still in the works.

**Comment by xhlulu** [comment]
Thank you!

**Comment by cweill** [comment]
@xhlulu: There appear to be some problems with the notebooks. Can you please check them and resolve the conflict?

**Comment by xhlulu** [comment]
This should be good now! Thank you for the notice.

**Pull request closed without merging**
